version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
    environment:
      - NODE_ENV=development

  mysql_db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: node_template
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql_db", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 3
      timeout: 5s

volumes:
  mysql_data:
    driver: local
